### ISSUE TITLE
Adicionar função imprime e fazer a leitura de dados do exercício "Matriz Quadrada III" - 1557 (beecrowd)

### ISSUE THREAD

**Issue by JerffersonJunior** [EngSoft-UFMS/algortimos_e_programacao_1#14]
Realizar a leitura das informações do exercício e criar função para imprimir o resultado de acordo com a saída requisitada pelo beecrowd.

**Comment by LourdesOshiroIgarashi** [comment]
Link do exercício: [https://www.beecrowd.com.br/judge/pt/problems/view/1557](url)

**Comment by LourdesOshiroIgarashi** [comment]
Podemos implementar a função imprime do exercício da seguinte forma:

1. Definimos a função imprime(matriz), que recebe a matriz como parâmetro.
3. Determinamos o tamanho do campo de formatação T. 
4. Encontramos o maior número na matriz usando a expressão max(max(linha) for linha in matriz). 
5. Calculamos o número de dígitos desse maior número usando len(str(maior_numero)).
6. Em seguida, usamos dois loops aninhados para percorrer a matriz e imprimir os elementos formatados.
7. Usamos a função str.rjust(T) para justificar à direita cada elemento e formatá-lo com o tamanho T.
8. Imprimimos cada elemento seguido de um espaço usando print(elemento_formatado, end=' ').
9. Após imprimir uma linha da matriz, usamos print() para imprimir uma nova linha.
10. No final de imprimir a matriz completa, usamos print() novamente para imprimir uma linha em branco.

**Comment by LourdesOshiroIgarashi** [comment]
Podemos fazer a leitura de dados do exercício da seguinte forma:

1. Dentro do loop, lemos a ordem da matriz N a partir da entrada padrão usando int(input()).
2. Se o valor de N for igual a zero, saímos do loop usando break.
3. Caso contrário, chamamos a função cria_matriz(N) para construir a matriz.
