### ISSUE TITLE
Adicionar a função cria_matriz do exercício "Matriz Quadrada III"  - 1557 (beecrowd)

### ISSUE THREAD

**Issue by JerffersonJunior** [EngSoft-UFMS/algortimos_e_programacao_1#15]
Criar função para formar a matriz que será trabalhada no exercício.

**Comment by LourdesOshiroIgarashi** [comment]
Link do exercício: [https://www.beecrowd.com.br/judge/pt/problems/view/1557](url)

**Comment by LourdesOshiroIgarashi** [comment]
Descrição do exercício  "Matriz Quadrada III" - 1557:

Escreva um algoritmo que leia um inteiro N (0 ≤ N ≤ 15), correspondente a ordem de uma matriz M de inteiros, e construa a matriz de acordo com o exemplo abaixo.

Entrada
A entrada consiste de vários inteiros, um valor por linha, correspondentes as ordens das matrizes a serem construídas. O final da entrada é marcado por um valor de ordem igual a zero (0).

Saída
Para cada inteiro da entrada imprima a matriz correspondente, de acordo com o exemplo. Os valores das matrizes devem ser formatados em um campo de tamanho T justificados à direita e separados por espaço, onde T é igual ao número de dígitos do maior número da matriz. Após o último caractere de cada linha da matriz não deve haver espaços em branco. Após a impressão de cada matriz deve ser deixada uma linha em branco.

Exemplo de Entrada	
1

2

3

4

5

0

Exemplo de Saída
1

1 2
2 4

 1  2  4
 2  4  8
 4  8 16

 1  2  4  8
 2  4  8 16
 4  8 16 32
 8 16 32 64

  1   2   4   8  16
  2   4   8  16  32
  4   8  16  32  64
  8  16  32  64 128
 16  32  64 128 256

**Comment by LourdesOshiroIgarashi** [comment]
Podemos implementar a função cria_matriz da seguinte forma:

1. Primeiro, definimos a função cria_matriz(N), que recebe um parâmetro N correspondente à ordem da matriz a ser construída.
2. Criamos uma lista vazia chamada matriz para armazenar os elementos da matriz.
3. Dentro da função cria_matriz(N), usamos dois loops aninhados para construir a matriz.
4. O primeiro loop, for i in range(N), percorre as linhas da matriz.
5. O segundo loop, for j in range(N), percorre as colunas da matriz.
6. Para cada posição (i, j) na matriz, calculamos o valor do elemento usando a fórmula 2 ** (i + j).
7. Adicionamos o elemento à lista linha.
8. Adicionamos a lista linha à matriz.
9. A função cria_matriz (N) retorna a matriz construída.
