### ISSUE TITLE
Otimizar resolução do exercício "Notas e Moedas" - 1021 (beecrowd) 

### ISSUE THREAD

**Issue by JerffersonJunior** [EngSoft-UFMS/algortimos_e_programacao_1#26]
Realizei a submissão do exercício, aceito pelo beecrowd, porém gostaria de uma melhoria em sua legibilidade para melhor entendimento. Para quem quiser trabalhar com esse problema, gostaria que fosse feita alguma função ou uma forma diferente para poder diminuir o seu tamanho.

**Comment by JerffersonJunior** [comment]
Descrição do exercício "Notas e Moedas" - 1021:

Leia um valor de ponto flutuante com duas casas decimais. Este valor representa um valor monetário. A seguir, calcule o menor número de notas e moedas possíveis no qual o valor pode ser decomposto. As notas consideradas são de 100, 50, 20, 10, 5, 2. As moedas possíveis são de 1, 0.50, 0.25, 0.10, 0.05 e 0.01. A seguir mostre a relação de notas necessárias.

Entrada
O arquivo de entrada contém um valor de ponto flutuante N (0 ≤ N ≤ 1000000.00).

Saída
Imprima a quantidade mínima de notas e moedas necessárias para trocar o valor inicial, conforme exemplo fornecido.

Obs: Utilize ponto (.) para separar a parte decimal.

----

#Resolução que enviei: 

valor = float(input())
vr = int(valor)
valor = valor100
vr = vr100
vc = valor-vr
vr = vr/100

n100 = vr//100
vr = vr%100 
n50 = vr//50
vr = vr%50
n20 = vr//20
vr = vr%20
n10 = vr//10
vr = vr%10
n5 = vr//5
vr = vr%5 
n2 = vr//2
vr = vr%2
m1 = vr//1.00
vr = vr%1.00

m050 = vc//50
vc = vc%50 
m025 = vc//25
vc = vc%25 
m010 = vc//10
vc = vc%10 
m005 = vc//5
vc = vc%5 
m001 = vc//1

print('NOTAS:')
print('%d nota(s) de R$ 100.00'%(n100))
print('%d nota(s) de R$ 50.00'%(n50))
print('%d nota(s) de R$ 20.00'%(n20))
print('%d nota(s) de R$ 10.00'%(n10))
print('%d nota(s) de R$ 5.00'%(n5))
print('%d nota(s) de R$ 2.00'%(n2))
print('MOEDAS:')
print('%d moeda(s) de R$ 1.00'%(m1))
print('%d moeda(s) de R$ 0.50'%(m050))
print('%d moeda(s) de R$ 0.25'%(m025))
print('%d moeda(s) de R$ 0.10'%(m010))
print('%d moeda(s) de R$ 0.05'%(m005))
print('%d moeda(s) de R$ 0.01'%(m001))

**Comment by JerffersonJunior** [comment]
Link do exercício: ["Notas e Moedas" - 1021](https://www.beecrowd.com.br/judge/pt/problems/view/1021)

**Comment by rafaelTsu** [comment]
Você pode criar uma função que receba pelo parâmetro o vr e o valor da nota, para te retornar a quantidade de notas necessárias desse valor. Ficaria algo assim:

`def calcula_notas(vr, valorNota)`
`    return vr//valorNota`

Dessa forma, não precisaria realizar a conta diretamente no código principal.
